Blogger\UserBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: Blogger\UserBundle\Repository\UserRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
                
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
    lifecycleCallbacks: {  }